AWSTemplateFormatVersion: "2010-09-09"
Resources:
  LambdaExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "sneaker-tracker-lambda-execution-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "SneakerTrackerLambdaExecutionPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "*"
              - Effect: "Allow"
                Action:
                  - "s3:GetObject"
                Resource: !Sub "arn:aws:s3:::sneaker-tracker-bucket/*"

  SneakerTrackerFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      FunctionName: "SneakerTrackerFunction"
      Handler: "sneaker_tracker_lambda.lambda_handler"
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: "sneaker-tracker-bucket"
        S3Key: "sneaker_tracker_lambda.zip"
      Runtime: "python3.8"
      MemorySize: 128
      Timeout: 30
