name: Deploy CloudFormation Stack

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Convert Python code to zip
        run: |
          zip -r sneaker_tracker_lambda.zip src/sneaker_tracker_lambda.py

      - name: Create or update S3 bucket
        run: |
          aws cloudformation deploy \
            --template-file infrastructure/s3-bucket.yml \
            --stack-name sneaker-tracker-bucket-stack \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              BucketName=sneaker-tracker-bucket

      - name: Wait for S3 bucket to be available
        run: |
          echo "Waiting for S3 bucket to be available..."
          aws s3api wait bucket-exists --bucket sneaker-tracker-bucket

      - name: Upload code to S3
        run: |
          echo "Uploading Lambda code to S3..."
          aws s3 cp sneaker_tracker_lambda.zip s3://sneaker-tracker-bucket/sneaker_tracker_lambda.zip

      - name: Verify S3 upload
        run: |
          aws s3 ls s3://sneaker-tracker-bucket/ --recursive

      - name: Deploy CloudFormation Stack for Lambda
        run: |
          aws cloudformation deploy \
            --template-file infrastructure/lambda.yml \
            --stack-name sneaker-tracker-lambda-stack \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              LambdaFunctionName=SneakerTrackerFunction \
              BucketName=sneaker-tracker-bucket\
              S3Key=sneaker_tracker_lambda.zip
